import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import '@/app/globals.css';


const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Regular, SemiBold, Bold
  variable: '--font-inter',
});

export const metadata = {
  title: "deadsweetpotato",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.variable}
      >
        {children}
      </body>
    </html>
  );
}
